run:
  deadline: 5m
linters-settings:
  lll:
    line-length: 170
  dupl:
#    The threshold is increased because we have some duplicated test code for pkg/webhook to support
#    k8s.io/api/admission/v1beta1, we can change this back when we drop the support and remove the legacy code completely.
#    threshold: 400
    threshold: 1500
issues:
  # don't skip warning about doc comments
  exclude-use-default: false

  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
  - linters: [errcheck]
    text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
linters:
  disable-all: true
  enable:
  - misspell
  - structcheck
  - golint
  - govet
  - deadcode
  - errcheck
  - varcheck
  - goconst
  - unparam
  - ineffassign
  - nakedret
  - gocyclo
  - lll
  - dupl
  - goimports
  - golint
