# Requires: kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user USER
apiVersion: v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: crew-system

bases:
- ../../base

resources:
- firstmate_crd.yaml
- manager_rbac.yaml
- crew_namespace.yaml

patchesStrategicMerge:
- manager_image_patch.yaml

imageTags:
  - name: pwittrock/controller-manager
    newTag: v1
