//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package pkg

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosPod) DeepCopyInto(out *ChaosPod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosPod.
func (in *ChaosPod) DeepCopy() *ChaosPod {
	if in == nil {
		return nil
	}
	out := new(ChaosPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosPod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosPodList) DeepCopyInto(out *ChaosPodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosPod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosPodList.
func (in *ChaosPodList) DeepCopy() *ChaosPodList {
	if in == nil {
		return nil
	}
	out := new(ChaosPodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosPodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosPodSpec) DeepCopyInto(out *ChaosPodSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	in.NextStop.DeepCopyInto(&out.NextStop)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosPodSpec.
func (in *ChaosPodSpec) DeepCopy() *ChaosPodSpec {
	if in == nil {
		return nil
	}
	out := new(ChaosPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosPodStatus) DeepCopyInto(out *ChaosPodStatus) {
	*out = *in
	in.LastRun.DeepCopyInto(&out.LastRun)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosPodStatus.
func (in *ChaosPodStatus) DeepCopy() *ChaosPodStatus {
	if in == nil {
		return nil
	}
	out := new(ChaosPodStatus)
	in.DeepCopyInto(out)
	return out
}
