# Requires: kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user USER
apiVersion: v1beta1
kind: Kustomization

resources:
- rbac.yaml
- manager.yaml

vars:
- fieldref: {}
  name: WEBHOOK_SECRET_NAME
  objref:
    apiVersion: v1
    kind: Secret
    name: webhook-server-secret
