// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
	apiv1 "sigs.k8s.io/controller-runtime/examples/applyconfig/api/v1"
)

// FooApplyConfiguration represents a declarative configuration of the Foo type for use
// with apply.
type FooApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:",inline"`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	NonNullableField                     *string `json:"nonNullableField,omitempty"`
	NullableField                        *string `json:"nullableField,omitempty"`
}

// WithNonNullableField sets the NonNullableField field in the declarative configuration to the given value
func (b *FooApplyConfiguration) WithNonNullableField(value string) *FooApplyConfiguration {
	b.NonNullableField = &value
	return b
}

// WithNullableField sets the NullableField field in the declarative configuration to the given value
func (b *FooApplyConfiguration) WithNullableField(value string) *FooApplyConfiguration {
	b.NullableField = &value
	return b
}

// FooApplyConfiguration represents a declarative configuration of the Foo type for use
// with apply.
func Foo() *FooApplyConfiguration {
	return &FooApplyConfiguration{}
}
func (ac *FooApplyConfiguration) GetReferenceType() runtime.Object {
	return &apiv1.Foo{}
}

func (ac *FooApplyConfiguration) GetName() string {
  return *ac.ObjectMetaApplyConfiguration.Name
}

func (ac *FooApplyConfiguration) GetNamespace() string {
  return *ac.ObjectMetaApplyConfiguration.Namespace
}
