name: Upload binaries to release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    name: Upload binaries to release
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # tag=v7.0.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Generate release binaries
      run: |
        make release
    - name: Release
      uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # tag=v3.0.2
      with:
        draft: false
        files: tools/setup-envtest/out/*
